### ISSUE TITLE
how to import arcgis-js-api based on ng2-webpack-starter

### ISSUE THREAD

**Issue by dyh333** [hassanqaiser/hassanqaiser.github.io#1]
@hassanqaiser , did you import arcgis-js-api based on ng2-webpack-starter? could you commit a repo to tell me how to do, thanks.

**Comment by hassanqaiser** [comment]
@dyh333 let me create a repo and will send you the link shortly.... I will commit to your repo as well..... please allow me 1 days thanks

**Comment by hassanqaiser** [comment]
@dyh333 please find the repository which is working,

https://github.com/hassanqaiser/angular2_webpack2_esri

**Comment by dyh333** [comment]
@hassanqaiser  thanks your repo. I have clone one and run on local, but it seems report a error "Cannot find name 'LegendOptions'" on app\map.service.ts
![image](https://cloud.githubusercontent.com/assets/1221313/19188894/880d0ce0-8cc7-11e6-9a89-e73556730884.png)

first, I run the npm install, and then run npm start. is there any arcgis lib should I install by global?

**Comment by dyh333** [comment]
I have sovled it. thanks your repo.

**Comment by hassanqaiser** [comment]
@dyh333 I am very much occupied these days, please tell us how did u solve?
